config/routes.rb
Punch::Application.routes.draw do
  resources :projects

  resource :user_session, :only => [:new, :create, :destroy]

  resources :users, :except => [:index]

  match '/signup' => 'users#new', :as => :signup
  match '/logout' => 'user_sessions#destroy', :as => :logout

  root :to => "user_sessions#new", :as => :login

end

app/models/project.rb
class Project < ActiveRecord::Base

  belongs_to :user

  attr_accessible :user_id, :preview_path

  validates_presence_of :user_id, :preview_path
  
  
end

app/models/user.rb
class User < ActiveRecord::Base
  
  has_many :projects
  
  attr_accessible :email, :password, :password_confirmation

  authenticates_with_sorcery!
  
  validates_length_of :password, :minimum => 8, :message => "password must be at least 8 characters in length", :if => :password
  validates_confirmation_of :password, :message => "should match confirmation", :if => :password

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :require_login
  
  def require_logged_out
    if logged_in?
      redirect_to current_user
    else
      true
    end
  end
  

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  
  before_filter :require_login
  
  def new
    @project = Project.new
  end

  def create
    uploaded_io = params[:project][:preview] #public-> id/projects/index
    preview_path = "uploads/#{uploaded_io.original_filename}"
    File.open(Rails.root.join('public', preview_path), 'wb') do |file|
      file.write(uploaded_io.read)
    end
    
    @project = Project.new
    @project.user = current_user
    @project.preview_path = "/" + preview_path
    
    if @project.save
      flash[:notice] = "Project Saved!"
      redirect_to @project
    else
      flash[:error] = "Something went wrong"
      render :new
    end
  end

  def show
    @project = Project.find params[:id] 
  end
  
  def index
    
  end

  def edit
  
  end

  def update
  
  end

  def destoy
  
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  
  skip_before_filter :require_login, :except=>:destroy
  before_filter :require_logged_out, :only => [:new, :create]

  def new
    @user = User.new
  end

  def create
    if @user = login(params[:user][:email], params[:user][:password])
      redirect_to @user
    else
      @user = User.new( params[:user] )
      render :new
    end
  end

  def destroy
    logout
    redirect_to '/'
    
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  skip_before_filter :require_login, :only => [:new, :create] 
  before_filter :require_logged_out, :only => [:new, :create]
  
  #GET /users/
  def new
    @user = User.new
  end

  #POST /users/
  def create
    @user = User.new params[:user]
    if @user.save
      flash[:notice] = "Welcome to Punch!"
      #log person in here
      redirect_to @user
    else
      flash[:error] = "You done fucked up"
      render :new
    end
  end

  #GET /users/:id/edit
  def edit
  end

  #PUT /users/:id
  def update
  end

  #GET /users/:id
  def show
    @user = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Punch</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
    <body>
        <div id="pgcontainer">
            <div id="pgcontent">
                <%= flash[:notice] %>
                <%= flash[:error]%>
                <% if logged_in? %>
	                <%= link_to "logout", logout_path %>
                    <% end %>
                <%= yield %>
            </div>
        </div>
    </body>
</html>

app/views/projects/new.html.erb
<h1>Let's create something!</h1>
<%= form_for(@project, :multipart => true) do |f| %>
	<% if @project.errors.any? %>
  		<div id="error_explanation">
    		<h2><%= pluralize(@project.errors.count, "error") %> your project was not saved because:</h2>
			<ul>
    			<% @project.errors.full_messages.each do |msg| %>
      				<li><%= msg %></li>
    			<% end %>
    		</ul>
  		</div>
	<% end %>
	<div class="file_field">
		<%= f.label :preview, 'Choose Preview File' %><br>
		<%= f.file_field :preview %>
	</div>

	<div class="actions">
		<%= f.submit "Create!"%>
	</div>
<%end%>

app/views/projects/show.html.erb
<h1>Hey look a thing</h1>
<%= link_to "Back to Projects", user_path(current_user) %>
<p>
<img src="<%= @project.preview_path %>">

app/views/user_sessions/new.html.erb
<h1>Log in</h1>
<%= form_for(@user, :url=>user_session_path) do |f| %>
	<div class="field">
		<%= f.label :email %><br>
		<%= f.text_field :email%>
	</div>
	<div class="field">
		<%= f.label :password %><br>
		<%= f.password_field :password %>
	</div>
	<div class="actions">
		<%= f.submit "Log in"%>
	</div>
<%end%>
    <p class="smalltext">
        <%= link_to "sign up", signup_path %>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/new.html.erb
<h1>Sign Up!</h1>
<%= form_for(@user) do |f| %>
	<% if @user.errors.any? %>
  		<div id="error_explanation">
    		<h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
			<ul>
    			<% @user.errors.full_messages.each do |msg| %>
      				<li><%= msg %></li>
    			<% end %>
    		</ul>
  		</div>
	<% end %>
	<div class="field">
		<%= f.label :email %><br>
		<%= f.text_field :email%>
	</div>
	<div class="field">
		<%= f.label :password %><br>
		<%= f.password_field :password %>
	</div>
	<div class="field">
		<%= f.label :password_confirmation, "Confirm" %><br>
		<%= f.password_field :password_confirmation %>
	</div>
	<div class="actions">
		<%= f.submit "Sign up!"%>
	</div>
<%end%>

<p class="smalltext">
    <%= link_to "log in", login_path %>

app/views/users/show.html.erb
<div id="userhead">
    <h1><%= @user.email %>'s Projects</h1>
    <%= link_to "New Project", new_project_path %>
    <p>
</div>
<table>
    <% @user.projects.each do |project| %>
        <tr>
            <td><%= image_tag project.preview_path %>
            </td>
        </tr>
        <!--Project Index here-->
    <% end %>
</table>